### PR TITLE
Added 2nd Bundesliga & Bundesliga refresh

### PR DESCRIPTION
**Pull request by raphipod**
- Added 2nd Bundesliga
- Bundesliga refresh (relegations & promotions)

I'm currently testing it, I will report back if I see anything that doesn't work.

### CODE REVIEW

**Comment by raphipod** [comment]
Seems like we have an error:

```
The settings of extension colosseum@sereneblue had an error:

Error: GSettings key bund-spgf not found in schema org.gnome.shell.extensions.colosseum


Stack trace:

_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:575:23
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:527:30
_init@/home/rkerscher/.local/share/gnome-shell/extensions/colosseum@sereneblue/prefs.js:161:24
_addTeam@/home/rkerscher/.local/share/gnome-shell/extensions/colosseum@sereneblue/prefs.js:85:23
_init@/home/rkerscher/.local/share/gnome-shell/extensions/colosseum@sereneblue/prefs.js:51:26
buildPrefsWidget@/home/rkerscher/.local/share/gnome-shell/extensions/colosseum@sereneblue/prefs.js:238:13
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:219:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
I'm trying to look for what's wrong here.

**Edit: Seems like I forgot to add the new teams into the gschema file. I'm working on it. Next commit should work.**

**Comment by raphipod** [comment]
I've now added all new teams into the gschema file, compiled it successfully. But it now complains with a different error:

```
The settings of extension colosseum@sereneblue had an error:

TypeError: this[("_" + followed)] is null


Stack trace:

_init@/home/rkerscher/.local/share/gnome-shell/extensions/colosseum@sereneblue/prefs.js:44:17
buildPrefsWidget@/home/rkerscher/.local/share/gnome-shell/extensions/colosseum@sereneblue/prefs.js:238:13
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:219:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

Do you know what's wrong here? I had suspected the whitespace I've put in to the gschemas-file for clarity, but I've already cleaned it up.
It's probably something very simple, but I am not sure.

**Comment by sereneblue** [comment]
Hi @raphipod, thanks for contributing!

I've reviewed your changes and made a small updates:

1. I've restored the previous teams you removed. I think it's better to comment them out for the season.
2. I've added a missing preference for Bund 2. 
3. The issue you encountered above was caused because there was missing UI code for the new league. I've updated the UI file with the changes to resolve this.

I'll merge the changes and will release an update soon.

**Comment by raphipod** [comment]
All right! Thank you for clarifying the error.

**Pull request merged**
